### ISSUE TITLE
vdk properties --list plain prints secret variables

### ISSUE THREAD

**Issue by v-ivandochev** [vmware/versatile-data-kit#1261]
Hi Team,

I created a data job (some_data_job) using vdk. Then I want to add some credentials to be stored as env variables. If I use:

vdk properties -n some_data_job -t some_team --set-secret password

I get a prompt like I should and the entered password ("mypassword") is hidden (as it should be).

BUT, if I then do:

!vdk properties -n some_data_job -t some_team --list

I get:

key       value
--------  ------------------
password  mypassword

That seems like a bug/bad behaviour. Data job access is controlled by team membership. So anyone in a team can check anyone else's data jobs. This means any team member can download and see the values for secret variables of any other. That seems strange...

I think the right way to solve this is to make the command --list mask all variables marked as 'secret' variables, like so:

key                         value
--------                   ------------------
myvariable             some_value
mysecretvariable   *********

In this case, one can never see what they have given as secret variable, yes, but they can always delete it and create a new one (if say they forget what they have given). In any case, plain printing a secret variable seems strange...

For unrelated reasons I cannot use a service user account, so this here is a make-or-break thing for me and some from my team at vmware.

**Comment by tozka** [comment]
`vdk properties --secure` is meant to allow users to pass properties using secure input.

 It's considered bad practice to pass any type of sensitive data by passing command line parameters directly because 
- the sensitive data (e.g password) is leaked into the process table, and thus visible to anybody running `ps` on the system
- the sensitive data is leaked into your shell's history file so can be retrieved later if someone else have access to the machine.

For example `vdk properties --set key sensitive-info`  is bad. 
Instead prompt is recommended which is what `vdk properties --secure` does. 

On the other hand printing to stdout is pretty safe, since it's not logged anywhere by default.   Once you close the session (the terminal tab), the output will be forgotten. 


As far as authorization goes, if you have access to the properties using vdk run (job_input.get_all_properties() in a data job file) then logically you will have access using other commands (like `vdk properties`) 


> For unrelated reasons I cannot use a service user account, so this here is a make-or-break thing for me and some from my team at vmware.
I am not sure I understand the request. But it does seem something different from this ticket. Feel free to open a new ticket. and explain there in detail what is the challenge.

**Comment by v-ivandochev** [comment]
10x for the reply.

1) I do not see vdk properties --secure anywhere in vdk properties --help. I see only 
--set-secret TEXT               Set key value property which is a secret. It
                                          behaves almost the same way as --set.The
                                          difference from --set is that it will be
                                         prompted and input would be masked.

As per the help: vdk properties help:

  Properties are key value pairs that can be set per data job.      Job
  properties are most commonly used to:

      * store credentials securely

So, set-secret is meant to store credentials securely. **That is all fine.**

2) My problem is **not** with --set or --set-secret, it is with **--list.** 

The problem is that by having --list printing to stdout the value of a secret variable you allow all team members access to all other's secret variables. So if a team has to use personal credentials in a datajob, then their personal credentials will be visible to all team members. Because any one team member can download a datajob of another team member, run vdk properties list and see in plain text the secret credentials.

This can be solved simply if you have --list **not** print to stdout, but mask the values of secret variables. That solves it. In that case, do you lose anything? What is the purpose of this print not being masked?

Cheers

**Comment by sabadzhiev** [comment]
Triaged. Closed as stale.
