### ISSUE TITLE
Broken data job after latest vdk-core changes

### ISSUE THREAD

**Issue by dakodakov** [vmware/versatile-data-kit#1462]
**Describe the bug**
One of our data jobs has started failing with a platform as a results of changes between the following vdk-core builds:
0.3.713658168 (stable) - 0.3.723457889 (broken)
Here's the problematic job
[job-user-error.zip](https://github.com/vmware/versatile-data-kit/files/10285446/job-user-error.zip)

**Steps To Reproduce**
1. Run the attached job
2. It should finish with an user error, but after the latest changes - it doesn't

**Expected behavior**
An user error is thrown and the appropriate exit code is return after the execution of the attached job.

**Comment by tozka** [comment]
I recently made a change in the behavior of job_input.get_managed_connection() to be per its contract -> https://github.com/vmware/versatile-data-kit/pull/1410 

This is the only change between the "bad" and the "good" versions. 

The actual problem is a bit different from what is described: 

* The user code (which I could see) relies on job_input.get_managed_connection() during initialization. 
* Until now it returned a non-connected managed connection .
* But it now tries to connect as it connects it lacks proper credentials and fails.
