### ISSUE TITLE
Wrap exceptions coming from user code in domain-specific errors

### ISSUE THREAD

**Issue by DeltaMichael** [vmware/versatile-data-kit#2679]
### Overview

We should decide if we want to wrap user code errors in vdk errors. The added benefit of wrapping is that we can make use of the new error format

[Wrapped](https://pastebin.com/raw/AsjDeyHZ)
[Not wrapped (current)](https://pastebin.com/raw/1HGfDqye)

### Acceptance criteria
1. Sync with rest of team and decide if we want to wrap
2. Implement wrapping depending on sync result

**Comment by sabadzhiev** [comment]
Discussed with @antoniivanov  and @DeltaMichael . This will not be implemented and closed.

**Comment by antoniivanov** [comment]
The question is to re-raise the original error or wrap it in a framework-specific exception :

Cons / pros analytics

**Re-raise Original Error**
- Allows users to see the exact point of failure in the code they are running.
- Easier for users to debug, as they get the original traceback.
- Users familiar with the libraries being used won't have to learn new error types.
**Wrap in Framework Exception:**
- Provides an opportunity to add more information about why the error might have occurred within the framework's logic.
 
So the best is to decide based on per-case basis and not adapt general rule. 

Guidelines 
-  If the error is due to a user's misuse of the framework, a framework-specific error will likely be more helpful.
- If the error is due to an underlying library or user code that the framework is running, the original error might be more useful for debugging.
- if extra information can be added that would help troubleshooting then wrapping the exception can be benefitial.
