### ISSUE TITLE
GraphQL API - optimize loading of deployments

### ISSUE THREAD

**Issue by mivanov1988** [vmware/versatile-data-kit#450]
**What is the feature request? What problem does it solve?**
Currently the API loads all deployments from Kubernetes regardless of filters. This is very inefficient and resource intensive (memory, network traffic, etc.).
If we have 2000 jobs that have one deployment each and filter them by _team_ that has 100 jobs, the API will always load 2000 deployments instead of 100 and it will filter them into the memory.
The only deployment filter we support is _enabled_. After #421 we can do the filtering by _deployment.enabled_ directly in the database by using _data_job.enabled_.

**Suggested solution**

1. If _deployment.enabled_ filter is provided do the filtering directly in the database by using _data_job.enabled_.
2. Load deployments during the post pagination phase (_GraphQLDataFetchers.populateDataJobsPostPagination_). In this way we will load only the required deployments by job names.
Sample deployments loading (https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors):
   ```java
   String fieldSelector = "metadata.name in ( job1, job2, job3 )"; 
   cronJobs = new BatchV1beta1Api(client).listNamespacedCronJob(namespace, null, null, fieldSelector, null, null, null, null, 
   null);
   ```
**Acceptance criteria**
The API should load only the required deployments.

**Comment by tpalashki** [comment]
It turns out that field selectors in Kubernetes do not support set-based requirements (i.e. the `in` operator) and there seems to be no way of fetching only a subset of the cronjobs based on their names. One possible solution would be to add a label with the data job name to the cronjob template, but this would be problematic for current adopters as they would need to redeploy all existing data jobs and also adds redundant information to the cronjob template itself.

I am closing this story. This problem will be resolved eventually when we move the deployments entirely in the database and no longer query the Kubernetes API for them.
