### ISSUE TITLE
Add configurable offset_start_time and offset_end_time for Executions Logs URL

### ISSUE THREAD

**Issue by mivanov1988** [vmware/versatile-data-kit#638]
Some of the external logging systems that our customers use
have different time than the location where their Control Service  is deployed

This proposal is to introduce configurable offset
that will be added to both start_time and end_time varibles
during the building of logs URL for each particular execution.

**Comment by tozka** [comment]
Describe what is the problem? If I am correct it is time skew between logging service and control service can cause inaccuracy. 

It make sense to have an offset also because you can expect that logging solution and deployed Control Service to be in different timezones, we should not assume that we are in the same time zone.
