### ISSUE TITLE
Data job definition dir missing from example

### ISSUE THREAD

**Issue by vecorro** [vmware/versatile-data-kit#889]
**Describe the bug**
The following directory

 https://github.com/vmware/versatile-data-kit/tree/main/examples/ingest-csv-file-example

Is missing the directory with the data job definitions. It only has a CSV file in it.

**Comment by tozka** [comment]
That's the documentation I know about https://github.com/vmware/versatile-data-kit/wiki/Ingesting-local-CSV-file-into-Database 

There's no job code because the example doesn't need it. It uses `vdk ingest-csv` CLI command. 

The examples directory contains usually the source code while the article explaining the example is in a wiki. I will add a link to the wiki page (in PR 893). 

Thanks again for reporting all this! I
